.SH bashdoc
.PP
Documentation generator for bash applications.
.SS Documentation syntax
.PP
Bashdoc will evaluate some special comments into the source code.
The comments are prefixed with the following doc strings:
.TP
\f[V]# mod: modname\f[R]
The module name itself.
.TP
\f[V]# fun: funsignature\f[R]
The function signature, usually include parameters here, but not
describe them.
.TP
\f[V]# txt:\f[R]
Textual description of the previous declarated section (module or
function).
.TP
\f[V]# opt: param: ...\f[R]
Describe an option or parameter to a function.
.TP
\f[V]# env: VAR: ...\f[R]
Describe a environment variable called \f[V]$VAR\f[R].
.TP
\f[V]# use: ...\f[R]
Provides an example of use of the function or module.
.TP
\f[V]# api: ...\f[R]
Set the API name for this element.
The API name could be used to filter what functions or modules will be
documented in final output.
.SS Examples
.PP
Let\[cq]s suppose the following content of the file
\f[V]script.bash\f[R]
.IP
.nf
\f[C]
# mod: example
# txt: this module is an example for documentation.
#      The txt sections as also opt and env ones can
#      be multiline if lines are kept vertical aligned.

# fun: sum num1 num2
# txt: sum two numbers and output the result
# opt: num1: the first number to sum
# opt: num2: the second number to sum
# use: sum 1 3
# api: sum
sum ()
{
  echo \[dq]$(($1 + $2))\[dq]
}
\f[R]
.fi
.PP
Now you can generate the HTML with the command:
.IP
.nf
\f[C]
bashdoc -o doc.html script.bash
\f[R]
.fi
.SS Using API name
.PP
Le\[cq]ts suppose the previous example code, and we need to add more
functions there:
.IP
.nf
\f[C]
# fun: internal_sum num1
# txt: return zero (yes, it\[aq]s not very usefull function)
# api: internal
internal_sum ()
{
  echo 0
}
\f[R]
.fi
.PP
If we generate the HTML in the same way that we do previously, the
result HTML will contain two documented functions: \f[V]sum\f[R] and
\f[V]internal_sum\f[R], but we don\[cq]t want the second one in the
documentation.
Of course we can remove the doc strings from there, but then we loose
the documentation in the code too.
To avoid this problem we can use the API name.
If you look carefully, you can see that the api name in the first
function is \f[V]sum\f[R], and in the second one is \f[V]internal\f[R].
If we run bashdoc as following:
.IP
.nf
\f[C]
bashdoc -A sum -o doc.html script.bash
\f[R]
.fi
.PP
We will create documentation only for functions tagged as API
\f[I]sum\f[R].
Please note that if you force a specific API tag, then functions or
modules without declared API will be not documented.
.SS Using custom stylesheet
.PP
By default bashdoc using its own CSS stylesheet and HTML template, which
is pretty nice, by the way, but if you want to use your own style and/or
HTML template, you can use it passing paramenters \f[V]-s\f[R] (for
style) and \f[V]-t\f[R] (for template) to the bashdoc command.
.PP
Accepted styleshet is any file which contains valid CSS code.
Accepted template is any template accepted by pandoc.
.PP
For example:
.IP
.nf
\f[C]
bashdoc -s mystyle.css -t mytemplate.html -o doc.html script.bash
\f[R]
.fi
.PP
   *   *   *   *   *
.SH API Reference
.SS arg
.PP
The \f[V]arg\f[R] module provides a number of functions to parse
arguments from command line.
To use the \f[V]arg\f[R] module you need to create handler functions
which will be called during the parser process.
The handler functions should return the number of parameters comsumed
from the parameter list.
See example below for more information.
.SS Usage example
.IP
.nf
\f[C]
opt_quiet () {
    QUIET=true; return 1; # we consum only the -q param
}
create () { echo \[dq]$arguments\[dq] }
arg::opt MAIN -q --quiet   opt_quiet   \[aq]do not output messages\[aq]
arg::action create create \[aq]create new things\[aq]
arg::param create \[dq]arguments+\[dq]  \[aq]argument to create subcommand\[aq]
arg::parse \[dq]$\[at]\[dq]
\f[R]
.fi
.SS arg::opt \f[V]<action>\f[R] \f[V]<short>\f[R] \f[V]<long>\f[R] \f[V]<handler>\f[R] \f[V][help]\f[R]
.PP
set an option for a specific action argument.
.SS Parameters
.TP
\f[V]action\f[R]
the action for which the option will be added
.TP
\f[V]short\f[R]
the short form of the option (usually prefixed by \f[V]-\f[R])
.TP
\f[V]long\f[R]
the long form of the option (usually prefixed by \f[V]--\f[R])
.TP
\f[V]handler\f[R]
function to handler when option is present.
.SS arg::parse::opt::fail \f[V]<cmdline>\f[R]
.PP
exit program with error 2 (cmdline error) interpreting cmdline passed as
argument.
.SS Parameters
.TP
\f[V]cmdline\f[R]
the cmdline which fails.
.SS arg::parse::opt::long \f[V]<action>\f[R] \f[V]<option>\f[R] \f[V][option\f[R] \f[V]argument]\f[R]
.PP
set the specific long option for the action passed as argument.
The option can be suffixed with a colon (:) to specify a mandatory
argument.
.SS arg::parse::opt::short \f[V]<action>\f[R] \f[V]<option>\f[R] \f[V][option\f[R] \f[V]argument]\f[R]
.PP
set the specific short option for the action passed as argument.
The option can be suffixed with a colon (:) to specify a mandatory
argument.
.SS arg::action \f[V]<action>\f[R] \f[V]<handler>\f[R] \f[V][help_message]\f[R]
.PP
set a new action in argument parser.
.SS Parameters
.TP
\f[V]action\f[R]
the action name to add to the parser
.TP
\f[V]handler\f[R]
the function name to use as handler for this action.
.TP
\f[V]help_message\f[R]
a message to print on usage.
.SS arg::usage::action \f[V]<action>\f[R]
.PP
print usage information for the action passed as argument.
.SS arg:::main::help \f[V]<text>\f[R]
.PP
Set the main help for the program
.SS Parameters
.TP
\f[V]text\f[R]
the main help string for the program
.SS arg:::main::action \f[V]<fun>\f[R]
.PP
Set the function handler for main action, used when no action defined.
.SS Parameters
.TP
\f[V]fun\f[R]
the handler for the MAIN action.
.SS arg::usage
.PP
print main usage information
.SS Environment variables
.TP
\f[V]E\f[R]
the error code to return to OS on exit.
.SS arg::parse::action \f[V]<action>\f[R] \f[V][arguments]\f[R]
.PP
parse arguments starting with action passed as argument.
.SS arg::parse::arg \f[V]<action>\f[R] \f[V][arguments]\f[R]
.PP
parse arguments (not options) for specific action passed as argument.
.SS arg::parse \f[V][arguments]\f[R]
.PP
parse arguments according with previous configured parser.
.SS arg::param \f[V]<action>\f[R] \f[V]<parameter_name>\f[R] \f[V][help_str]\f[R]
.PP
add position parameter to parser.
.SS Parameters
.TP
\f[V]action\f[R]
action where add the parameter
.TP
\f[V]parameter_name\f[R]
the name of the paramenter
.TP
\f[V]help_str\f[R]
a help string for the parameter to show in usage
.SS cache
.PP
The \f[V]cache\f[R] module provides a simple in-memory cache.
.SS Usage example
.IP
.nf
\f[C]
cache::put \[dq]key\[dq] \[dq]val\[dq]
cache::get \[dq]key\[dq]
\f[R]
.fi
.SS cache::get \f[V]<key>\f[R]
.PP
get the value of the key from the potion in-memory cache.
.SS cache::put \f[V]<key>\f[R] \f[V]<value>\f[R]
.PP
save the content of the specified key to the in-memory cache.
.SS config
.PP
The \f[V]config\f[R] module allows you to read configuration file in
properties format
.SS Usage example
.IP
.nf
\f[C]
config::load configname ./config.properties
echo $(config::get configname key)
\f[R]
.fi
.SS config::load \f[V]<table>\f[R] \f[V]<file>\f[R]
.PP
read a configuration file passed as argument and save in the memory with
specific table name.
.SS Parameters
.TP
\f[V]table\f[R]
a name to identify the config table where file will be load.
.TP
\f[V]file\f[R]
path to a properties file to load.
.SS config::get \f[V]<table>\f[R] \f[V]<key>\f[R] \f[V][default]\f[R]
.PP
outputs the specified configuration key in the table passed as argument.
If key does not exists raise an error, unless default is passed as
argument, in that case return default values.
.SS Parameters
.TP
\f[V]table\f[R]
the table name where to search key.
.TP
\f[V]key\f[R]
the key to search in config table
.TP
\f[V]default\f[R]
default value to output if value is not found.
By default an error is raised.
.SS config::iter \f[V]<table>\f[R] \f[V]<pattern>\f[R]
.PP
iterate over a specific configuration using pattern passed as argument
and outputs keys with match.
.SS Parameters
.TP
\f[V]table\f[R]
the table name to iterate
.TP
\f[V]pattern\f[R]
a glob pattern to match in config keys.
.SS curl
.PP
The curl module offers a way to access to HTTP resources easily.
.SS curl::get \f[V]<url>\f[R]
.PP
get an object from url and output it to stdout
.SS Parameters
.TP
\f[V]url\f[R]
any URL valid for curl.
.SS Usage example
.IP
.nf
\f[C]
curl::get http://example.com
\f[R]
.fi
.SS curl::source \f[V]<url>\f[R]
.PP
sources a file from url
.SS Usage example
.IP
.nf
\f[C]
curl::source http://mydomain.com/file.bash
\f[R]
.fi
.SS doc
.PP
The \f[V]doc\f[R] module provides functions to convert bash source code
to HTML, using markdown and specific CSS themes.
.SS doc::read_blocks \f[V][api]\f[R]
.PP
read and print blocks readed from stdin which match with specific api
definition.
If api is not provided all elements will be documentated, if api is
provided, only elements with declared api matched with provided one will
be documented.
If api is provided, but is not declared in documentation, then item will
be documentated too.
.SS Parameters
.TP
\f[V]api\f[R]
a string which identify the API to be documented.
.SS Environment variables
.TP
\f[V]DOCSTRING\f[R]
The docstring comment which identify a special comment used for
documentation.
By default `sha-space' (# ).
.SS Usage example
.IP
.nf
\f[C]
doc::read_blocks v1 < script
\f[R]
.fi
.SS doc::output \f[V]<file>+\f[R]
.PP
Create intermediate markdown code required to produce final HTML.
.SS Environment variables
.TP
\f[V]TITLE\f[R]
The document title.
.TP
\f[V]AUTHOR\f[R]
The document author.
.TP
\f[V]DATE\f[R]
The date of the produced document.
.SS Usage example
.IP
.nf
\f[C]
doc::output file
\f[R]
.fi
.SS doc::generate \f[V]<file>+\f[R]
.PP
generate HTML for the specified files passed as arguments.
.SS Environment variables
.TP
\f[V]OUTPUT\f[R]
filename of the output file or stdout if not provided.
.SS Usage example
.IP
.nf
\f[C]
doc::generate file
\f[R]
.fi
.SS err
.PP
The \f[V]err\f[R] module offers a way to stop potion execution with a
traceback.
.SS err::trace
.PP
print to stderr a traceback of an error.
.SS Usage example
.IP
.nf
\f[C]
false || err::trace \[dq]Error because of false\[dq]
\f[R]
.fi
.SS main
.PP
The \f[V]main\f[R] module contain the specified potion body.
.SS main::init
.PP
print nice potion logo and some custom messages at the beginning.
.SS mutex
.PP
The \f[V]mutex\f[R] module provides a way to ensure critical region
access across different processes.
NOTE this module does not work fine on some filesystems, like NFS, AFS
and others.
.SS Usage example
.IP
.nf
\f[C]
mutex::run mymutex sleep 10 # run a sleep in a critical region
mutex::adquire mymutex
# do some critical changes
mutex::release mymutex
\f[R]
.fi
.SS mutex::adquire \f[V]<name>\f[R]
.PP
create a mutex or wait until mutex removed
.SS Parameters
.TP
\f[V]name\f[R]
the name to identify this mutex
.SS mutex::release \f[V]<name>\f[R]
.PP
release mutex by name
.SS Parameters
.TP
\f[V]name\f[R]
the name to identify this mutex
.SS mutex::run \f[V]<name>\f[R] \f[V]<command>\f[R] \f[V][args]\f[R]
.PP
run a command protected by mutex named as argument name.
.SS Parameters
.TP
\f[V]name\f[R]
the name to identify this mutex
.TP
\f[V]command\f[R]
the command to run
.TP
\f[V]args\f[R]
optional arguments to the command.
.SS os
.PP
The \f[V]os\f[R] module provides specified functions to guess the
operating system related variables.
.SS os::family
.PP
print to stdout the operating system family
.SS os::provider
.PP
print the operating system provider (formerly distribution).
.SS os::release
.PP
print to stdout the properly release of operating system provider.
.SS os::path \f[V]<file>\f[R]
.PP
return the path of a file in PATH
.SS Parameters
.TP
\f[V]file\f[R]
the file name to find the full path.
.SS Environment variables
.TP
\f[V]PATH\f[R]
contains the path to search file
.SS os.ubuntu
.PP
The \f[V]os.ubuntu\f[R] module extends \f[V]os\f[R] module adding
specific functions for Ubuntu based systems.
.SS os::relase::ubuntu
.PP
return specific relese for ubuntu operating systems.
.SS out
.PP
The \f[V]out\f[R] module provides functions to output messages in stderr
or stdout.
.SS out::log \f[V]<message>\f[R] \f[V][message_type]\f[R]
.PP
print to stdout a log line with specified message and prefixed by date
and message_type.
.SS Environment variables
.TP
\f[V]DATE_FORMAT\f[R]
defines the format for the datetime, in regular date(1) format.
.TP
\f[V]COLOR_DATE\f[R]
defines the color to use (if available) to print the date.
.TP
\f[V]COLOR_MESSAGE\f[R]
defines the color to use to print the message.
.TP
\f[V]COLOR_NONE\f[R]
defines the sequence to reset defined color.
.TP
\f[V]QUIET\f[R]
if true do not show any messages
.SS out::info \f[V]<message>\f[R]
.PP
print an informational message in stdout.
.SS Environment variables
.TP
\f[V]COLOR_INFO\f[R]
defines the color to be used in informational messages.
.SS out::fail \f[V]<message>\f[R]
.PP
print an informational message in stdout.
.PP
print an error message in stderr.
.SS Environment variables
.TP
\f[V]COLOR_FAIL\f[R]
defines the color to be used in this kind of messages.
E: if set exit program with error code defined in the variable
.SS out::warn \f[V]<message>\f[R]
.PP
print an informational message in stdout.
.PP
print a warning message in stderr.
.SS Environment variables
.TP
\f[V]COLOR_WARN\f[R]
defines the color to be used in this kind of messages.
.SS out::user \f[V]<message>\f[R]
.PP
print an informational message in stdout.
.PP
print a user defined message in stdout
.SS Environment variables
.TP
\f[V]COLOR_USER\f[R]
defines the color to be used in this kind of messages.
.SS proc
.PP
The \f[V]proc\f[R] module provides a number of functions to manage
parallel processes
.SS proc::waitn \f[V][number]\f[R]
.PP
wait for n procs to finished, or for everyone if no number specify
.SS Parameters
.TP
\f[V]number\f[R]
the number of proccess to wait for or none if wait for everyone.
.SS std
.PP
The \f[V]std\f[R] module contains a numer of standard functions usefull
to progamming in bash.
.SS std::quit
.PP
perform an exit clean of the running program.
.SS std::add_quit_handler \f[V]<func_name>\f[R]
.PP
Add func_name as handler to execute before quit the application.
When the application finished, then the functions registered as quit
handlers will be executed in the same order than they were registered.
.SS Parameters
.TP
\f[V]func_name\f[R]
the name of the function to be registered.
.SS Usage example
.IP
.nf
\f[C]
somefunc () { echo \[dq]exiting\[dq]; }
std::add_quit_handler somefunc
\f[R]
.fi
.SS std::hmac \f[V]<text>\f[R]
.PP
outputs the calculated HMAC using SHA1 for the text passed as argument.
.SS Parameters
.TP
\f[V]text\f[R]
a plain text to be hashed.
.SS Environment variables
.TP
\f[V]ALGO\f[R]
set the algorithm to use for calculate HMAC.
Valid values are: sha1, md5, sha256, sha512.
The proper helper tool must be installed on the system.
.SS Usage example
.IP
.nf
\f[C]
std::hmac \[dq]hello world\[dq]
ALGO=md5 std::hmac \[dq]hello world\[dq]
\f[R]
.fi
.SS std::mute \f[V]<command>\f[R]
.PP
mute outputs, including \f[V]stderr\f[R] when running a command, alias
or function
.SS Parameters
.TP
\f[V]command\f[R]
the command to run muted.
.SS std::strin \f[V]<str1>\f[R] \f[V]<str2>\f[R]
.PP
return true if \f[V]str2\f[R] is into \f[V]str1\f[R], or false
otherwise.
.SS Parameters
.TP
\f[V]str1\f[R]
the string which could be contain \f[V]str2\f[R] and wants to evaluate
.TP
\f[V]str2\f[R]
the string to find into \f[V]str1\f[R]
.SS Usage example
.IP
.nf
\f[C]
std::strin \[dq]somelargestring\[dq] \[dq]some\[dq]
\f[R]
.fi
.SS std::func \f[V]<func_name>\f[R]
.PP
return true if function name passed as argument is defined, or false
otherwise.
.SS std::arch
.PP
outputs the hardware architecture of the current host.
.SS std::timestamp
.PP
outputs the UNIX timestamp
.SS Environment variables
.TP
\f[V]TZ\f[R]
the timezone to use to print the timestamp, by default get the timezone
from the system.
.SS std::parse \f[V]<arg_string>\f[R]
.PP
parse an argument string in the form key=value and promote this
variables to environment.
The key \f[V]name\f[R] is mandatory.
If the first parameter has no key, key \f[V]name\f[R] is using by
default.
The \f[V]name\f[R] parameter must be the first one.
.SS Usage example
.IP
.nf
\f[C]
std::parse \[dq]name=Jhon\[dq] \[dq]age=90\[dq]
echo \[dq]$name has $age years old\[dq]
\f[R]
.fi
.SS std::run \f[V]<command>\f[R]
.PP
Run command passed as argument if $PRETEND is not set to true
.SS Environment variables
.TP
\f[V]PRETEND\f[R]
if true do nothing.
.SS std::installed \f[V]<command>\f[R]
.PP
return true if command is installed in path
.SS std::is_dir_empty \f[V]<dir>\f[R]
.PP
return true if dir is empty
.SS std::sort \f[V]<array>\f[R]
.PP
sort an array using qsort in pure bash (not very efficient) and return
the output to an special variable called \f[V]sort_ret\f[R].
.SS Environment variables
.TP
\f[V]sort_ret\f[R]
will contain the sorted array
.SS str2array \f[V]<string>\f[R] \f[V][separator]\f[R]
.PP
create a new array with the contents of the string, using separator
passed as argument.
.SS Parameters
.TP
\f[V]string\f[R]
the string to covert to array
.TP
\f[V]separator\f[R]
the character to use as separator, by default use comma.
.SS Usage example
.IP
.nf
\f[C]
str2array \[dq]one,two,three\[dq]
echo \[dq]${str2array_ret[\[at]]}\[dq]
\f[R]
.fi
.SS term
.PP
The \f[V]term\f[R] module provides functions related with terminal
configuration.
This module also define some useful color variables to be used in
\f[V]out\f[R] module.
.SS term::attached
.PP
return true if output is a terminal, false otherwise
.SS term::tcap \f[V]<capability>\f[R]
.PP
check if some capabilty is enabled in terminal
.SS term::init
.PP
initialize terminal, in theory you never need to call this function,
unless you want to change your terminal online.
.SS tmp
.PP
The \f[V]tmp\f[R] module provides functions to create and destroy
temporary directories.
Even if you don\[cq]t remove the temporary file or directoy explicitely,
the directory or file will be deleted when program exits.
.SS Environment variables
.TP
\f[V]TMPDIR\f[R]
a subdirectory into /tmp to use to create temporary files or
directories.
.TP
\f[V]BLIB_TMPDIR\f[R]
a full path to temporary directory to use to store files or other
directories.
.SS Usage example
.IP
.nf
\f[C]
tmp::create
# do some actions in current directory, which is temporary one
tmp::destroy
\f[R]
.fi
.IP
.nf
\f[C]
echo $(tmp::file)
\f[R]
.fi
.SS tmp::create \f[V]<dirname>\f[R]
.PP
create temporary directory and move working directory into it
.SS tmp::exit
.PP
exit the temporary directory, but not remove it.
.SS tmp::destroy
.PP
move to root directoy and remove temporary directory
.SS tmp::exists \f[V]<name>\f[R]
.PP
return true if the specified file name or directory name is a temporary
file or directory.
.SS tmp::file
.PP
print to stdout the name of unique temporary file.
.SS tmp::touch \f[V]<name>\f[R]
.PP
create a temporary file with specified name in temporary directory.
.SS version
.PP
The \f[V]version\f[R] module provides a number of functions to handle
version numbers.
.SS version::cmp \f[V]<version1>\f[R] \f[V]<version2>\f[R]
.PP
compare two version numbers, return -1 (255) if version1 is greater than
version2, return 1 if version2 is greater than version1 and 0 if both
are equal
.PP
   *   *   *   *   *
