#! /bin/bash
# mod: main
# txt: The ``main`` module contain the specified potion body.

VERSION="2.0.0"

# fun: main::init
# txt: print nice potion logo and some custom messages at the beginning.
main::init () {

out::user "    ${COLOR_WARN},   ,${COLOR_NONE}"
out::user "   ${COLOR_WARN}/////|${COLOR_NONE}"
out::user "  ${COLOR_WARN}///// |${COLOR_NONE} ${COLOR_INFO} _               _         _            ${COLOR_NONE}"
out::user " ${COLOR_WARN}|~~~|  |${COLOR_NONE} ${COLOR_INFO}| |__   __ _ ___| |__   __| | ___   ___ ${COLOR_NONE}"
out::user " ${COLOR_WARN}|===|  |${COLOR_NONE} ${COLOR_INFO}| '_ \\ / _\` / __| '_ \\ / _\` |/ _ \\ / __|${COLOR_NONE}"
out::user " ${COLOR_WARN}|   |  |${COLOR_NONE} ${COLOR_INFO}| |_) | (_| \\__ \\ | | | (_| | (_) | (__ ${COLOR_NONE}"
out::user " ${COLOR_WARN}|   |  |${COLOR_NONE} ${COLOR_INFO}|_.__/ \\__,_|___/_| |_|\\__,_|\\___/ \\___|${COLOR_NONE}"
out::user " ${COLOR_WARN}|   | /${COLOR_NONE}  ${COLOR_USER}version ${VERSION}${COLOR_NONE}"
out::user " ${COLOR_WARN}|===|/${COLOR_NONE}"
out::user " ${COLOR_WARN}'---'${COLOR_NONE}"
                                        

                                        
}

opt_files=""
# general options handlers
main::opt_version () { out::info "Bashdoc $VERSION"; exit 0;}
main::opt_title () { TITLE="$1"; return 2; }
main::opt_author () { AUTHOR="$1"; return 2; }
main::opt_output () { OUTPUT="$1"; return 2; }
main::opt_date () { DATE="$(date +%Y-%m-%d)"; return 1; }
main::opt_file () { opt_files="$opt_files $1"; return 2; }
main::opt_api () { API="$1"; return 2; }
main::opt_style () { __opt__style="$1"; echo "$@" ; return 2; }
main::opt_template () { __opt__template="$1"; return 2; }
main::opt_highlight () { __opt__highlight="$1"; return 2; }

# main function really
main::action () {
  main::init
  doc::generate "$@"
}

main () {
  arg::opt MAIN -V --version main::opt_version 'show program version number'
  arg::opt MAIN -T --title   main::opt_title   'set the title of the document'
  arg::opt MAIN -a --author  main::opt_author  'set the author of the document'
  arg::opt MAIN -o --output  main::opt_output  'set the output file name'
  arg::opt MAIN -d --include-date  main::opt_date   'add date to the document'
  arg::opt MAIN -f --file    main::opt_file         'add more section files'
  arg::opt MAIN -a --api     main::opt_api          'set api to be documented'
  arg::opt MAIN -s --style   main::opt_style        'path to CSS stylesheet'
  arg::opt MAIN -t --template  main::opt_template   'path to HTML template'
  arg::opt MAIN -H --highlight-theme  main::opt_highlight \
    'theme name to highlight code'

  arg::main::help "Generate documentation for bash programs"
  arg::main::action main::action

  arg::param MAIN "script+" \
    'Path or URL to script to create documentation'

  arg::parse "$@"
}
